---
- name: Deploy Web App
  hosts: node_1
  remote_user: ubuntu
  become: true

  tasks:
    - name: Ensure apache is installed
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true

    - name: Ensure git is installed
      ansible.builtin.apt:
        name: git
        state: present

    - name: Remove the deploy directory
      ansible.builtin.file:
        path: /var/www/html
        state: absent

    - name: Create the deploy directory
      ansible.builtin.file:
        path: /var/www/html
        state: directory

    - name: Deploy Web Application
      ansible.builtin.git:
        repo: https://github.com/CeeyIT-Solutions/food3.git
        dest: /var/www/html
        version: ansible
